import type { Metadata } from 'next';
import { Merriweather } from 'next/font/google';
import { Nunito } from 'next/font/google';
import './globals.css';

const merriweather = Merriweather({
  subsets: ['cyrillic'],
  weight: ['300', '400', '700'],
});

const nunito = Nunito({
  subsets: ['cyrillic'],
  weight: ['300', '400', '700'],
});

export const metadata: Metadata = {
  title: 'Movie Guesser',
  description: 'Generated by Narek',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
